board:
  title: "&6&lDESERT VILLAGE REPUTATION"
  refresh-seconds: 10

builder:
  standard-materials:
    - SANDSTONE
    - CUT_SANDSTONE
    - SMOOTH_SANDSTONE
    - CHISELED_SANDSTONE
    - TERRACOTTA
    - ORANGE_TERRACOTTA
    - YELLOW_TERRACOTTA
    - BROWN_TERRACOTTA
    - WHITE_TERRACOTTA
    - BRICKS
    - STONE_BRICKS
    - COBBLESTONE
    - STONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - MANGROVE_PLANKS
    - CHERRY_PLANKS
    - BAMBOO_PLANKS
    - OAK_LOG
    - SPRUCE_LOG
    - BIRCH_LOG
    - JUNGLE_LOG
    - ACACIA_LOG
    - DARK_OAK_LOG
    - MANGROVE_LOG
    - CHERRY_LOG
    - GLASS
    - GLASS_PANE
    - SANDSTONE_STAIRS
    - RED_SANDSTONE_STAIRS
    - SANDSTONE_SLAB
    - RED_SANDSTONE_SLAB
    - SANDSTONE_WALL
    - RED_SANDSTONE_WALL
  premium-materials:
    - GOLD_BLOCK
    - DIAMOND_BLOCK
    - NETHERITE_BLOCK
    - RED_SANDSTONE
    - CUT_RED_SANDSTONE
    - SMOOTH_RED_SANDSTONE
    - CHISELED_RED_SANDSTONE
    - RED_SANDSTONE_STAIRS
    - RED_SANDSTONE_SLAB
    - RED_SANDSTONE_WALL
    - SOUL_TORCH
    - SOUL_LANTERN
    - BELL
    - FLOWER_POT
    - DECORATED_POT
